import { Metadata } from "next";
import DashboardLayoutClient from "./DashboardLayout";
import "../../globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Website SID Desa Kab. Sumedang",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  if (!session) {
    redirect("/login");
    return null;
  }
  return <DashboardLayoutClient>{children}</DashboardLayoutClient>;
}
